=begin
#Money Forward Kessai API v2

#Money Forward Kessai REST API

The version of the OpenAPI document: 2.6.7
Contact: api.support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MfkOpenapiRubyClient::CreditFacilityApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreditFacilityApi' do
  before do
    # run before each test
    @api_instance = MfkOpenapiRubyClient::CreditFacilityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreditFacilityApi' do
    it 'should create an instance of CreditFacilityApi' do
      expect(@api_instance).to be_instance_of(MfkOpenapiRubyClient::CreditFacilityApi)
    end
  end

  # unit tests for get_credit_facilities_list
  # 与信枠の一覧を取得します。顧客IDや取引登録期間開始日・終了日で絞り込んで取得することもできます。
  # 与信枠一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 顧客IDを指定します。指定された顧客の与信枠を取得します。
  # @option opts [String] :customer_number 顧客番号を指定します。 指定された顧客の与信枠を取得します。
  # @option opts [String] :customer_examination_id 与信枠審査IDを指定します。指定された与信枠審査によって付与された与信枠を取得します。
  # @option opts [Array<String>] :status ステータスを指定します。該当するステータスの与信枠が返却されます。指定できる値は &#x60;expired&#x60;(期限切れ), &#x60;active&#x60;(適用中), &#x60;inactive&#x60;(未適用), の３種類のみです。ステータスは複数指定することができます。 複数指定する場合は&#x60;?status&#x3D;expired&amp;status&#x3D;active&#x60;もしくは&#x60;?status&#x3D;expired,active&#x60;のように指定してください。
  # @option opts [Time] :start_date_from 取引登録期間開始日が指定された日時よりも後の与信枠を取得します。指定された日時のものも含まれます。
  # @option opts [Time] :start_date_to 取引登録期間開始日が指定された日時よりも前の与信枠を取得します。指定された日時のものも含まれます。
  # @option opts [Time] :end_date_from 取引登録期間終了日が指定された日時よりも後の与信枠を取得します。指定された日時のものも含まれます。
  # @option opts [Time] :end_date_to 取引登録期間終了日が指定された日時よりも前の与信枠を取得します。指定された日時のものも含まれます。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [CreditFacilitiesList]
  describe 'get_credit_facilities_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_credit_facility
  # 与信枠IDを指定して対象与信枠１件を取得することができます。
  # 与信枠取得
  # @param credit_facility_id 対象の与信枠IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [CreditFacility]
  describe 'get_credit_facility test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
