=begin
#Money Forward Kessai API v2

#Money Forward Kessai REST API

The version of the OpenAPI document: 2.6.7
Contact: api.support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MfkOpenapiRubyClient::CustomerExaminationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomerExaminationApi' do
  before do
    # run before each test
    @api_instance = MfkOpenapiRubyClient::CustomerExaminationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerExaminationApi' do
    it 'should create an instance of CustomerExaminationApi' do
      expect(@api_instance).to be_instance_of(MfkOpenapiRubyClient::CustomerExaminationApi)
    end
  end

  # unit tests for create_customer_examination
  # 顧客を指定して与信枠審査を申請することができます。最長で申請後2営業日以内に審査いたします。&lt;br&gt; 自動与信枠審査をご利用の場合、こちらで増枠した金額は今後の与信枠付与に継続して利用されます。また、対象顧客のアラートは解消されます。&lt;br&gt; Sandbox環境では動作テストのため、任意の審査結果を指定することができます。[審査結果の操作](#environment_magic_number)を参照してください。
  # 与信枠審査申請
  # @param payload 与信枠審査申請情報です。
  # @param [Hash] opts the optional parameters
  # @return [CustomerExamination]
  describe 'create_customer_examination test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_examination
  # 与信枠審査IDを指定して対象与信枠審査１件を取得することができます。
  # 与信枠審査取得
  # @param customer_examination_id 対象の与信枠審査IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [CustomerExamination]
  describe 'get_customer_examination test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_examinations_list
  # 与信枠審査の一覧を取得します。顧客IDやステータスで絞り込んで取得することもできます。
  # 与信枠審査一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 顧客IDを指定します。指定された顧客に対する与信枠審査を取得します。
  # @option opts [String] :customer_number 顧客番号を指定します。
  # @option opts [String] :status 与信枠審査のステータスを指定します。未審査(&#x60;unexamined&#x60;)、審査通過(&#x60;passed&#x60;)、審査否決(&#x60;rejected&#x60;)のいずれかを指定してください。
  # @option opts [Time] :created_at_from 指定された日時以降に作成された与信枠審査を取得します。指定された日時に作成されたものも含まれます。 RFC3339の&#x60;date-time&#x60;(2019-04-01T10:36:43%2B09:00)で指定してください。
  # @option opts [Time] :created_at_to 指定された日時以前に作成された与信枠審査を取得します。指定された日時に作成されたものも含まれます。 RFC3339の&#x60;date-time&#x60;(2019-04-01T10:36:43%2B09:00)で指定してください。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [CustomerExaminationsList]
  describe 'get_customer_examinations_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
