=begin
#Money Forward Kessai API v2

#Money Forward Kessai REST API

The version of the OpenAPI document: 2.6.7
Contact: api.support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MfkOpenapiRubyClient::TaxRateType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MfkOpenapiRubyClient::TaxRateType do
  let(:instance) { MfkOpenapiRubyClient::TaxRateType.new }

  describe 'test an instance of TaxRateType' do
    it 'should create an instance of TaxRateType' do
      expect(instance).to be_instance_of(MfkOpenapiRubyClient::TaxRateType)
    end
  end
end
