=begin
#Money Forward Kessai API v2

#Money Forward Kessai REST API

The version of the OpenAPI document: 2.6.7
Contact: api.support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module MfkOpenapiRubyClient
  class InvoiceDeliveryMethod
    POSTING = "posting".freeze
    EMAIL = "email".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = InvoiceDeliveryMethod.constants.select { |c| InvoiceDeliveryMethod::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #InvoiceDeliveryMethod" if constantValues.empty?
      value
    end
  end
end
