=begin
#Money Forward Kessai API v2

#Money Forward Kessai REST API

The version of the OpenAPI document: 2.6.7
Contact: api.support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module MfkOpenapiRubyClient
  class TaxRateType
    NON_TAXABLE = "non_taxable".freeze
    NORMAL_8 = "normal_8".freeze
    NORMAL_10 = "normal_10".freeze
    REDUCED_8 = "reduced_8".freeze
    TRANSITIONAL_MEASURES_8 = "transitional_measures_8".freeze
    INAPPLICABLE = "inapplicable".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TaxRateType.constants.select { |c| TaxRateType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TaxRateType" if constantValues.empty?
      value
    end
  end
end
